name: tekmerion
description: Peace and predictability through a trustworthy record.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  uuid: ^4.4.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.6
  sqflite: ^2.4.3
  path: ^1.9.1
  file_picker: ^11.0.3
  pdfrx: ^2.4.7
  intl: ^0.20.3

  meta: any
  pdf: ^3.13.0
  archive: ^4.0.9
  share_plus: ^12.0.2
  json_schema: any
  timezone: ^0.11.1
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.4.2

flutter:
  uses-material-design: true
