name: tekmerion
description: Peace and predictability through a trustworthy record.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  uuid: ^4.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
